import { EmotionalState, Session } from "@/types/session";

export const emotionalStates: EmotionalState[] = [
  // Negative emotions (low to high intensity)
  {
    id: "depressed",
    label: "Depressed",
    gradient: ["#2C3E50", "#34495E"],
    intensity: 1,
    category: "negative",
  },
  {
    id: "sad",
    label: "Sad",
    gradient: ["#667eea", "#764ba2"],
    intensity: 2,
    category: "negative",
  },
  {
    id: "anxious",
    label: "Anxious",
    gradient: ["#FF6B6B", "#C44569"],
    intensity: 3,
    category: "negative",
  },
  {
    id: "stressed",
    label: "Stressed",
    gradient: ["#F7971E", "#FFD200"],
    intensity: 4,
    category: "negative",
  },
  {
    id: "angry",
    label: "Angry",
    gradient: ["#f093fb", "#f5576c"],
    intensity: 5,
    category: "negative",
  },
  // Neutral emotions
  {
    id: "neutral",
    label: "Neutral",
    gradient: ["#95A5A6", "#BDC3C7"],
    intensity: 6,
    category: "neutral",
  },
  // Positive emotions (low to high intensity)
  {
    id: "calm",
    label: "Calm",
    gradient: ["#4facfe", "#00f2fe"],
    intensity: 7,
    category: "positive",
  },
  {
    id: "focused",
    label: "Focused",
    gradient: ["#43e97b", "#38f9d7"],
    intensity: 8,
    category: "positive",
  },
  {
    id: "happy",
    label: "Happy",
    gradient: ["#fa709a", "#fee140"],
    intensity: 9,
    category: "positive",
  },
  {
    id: "energized",
    label: "Energized",
    gradient: ["#30cfd0", "#330867"],
    intensity: 10,
    category: "positive",
  },
];

export const sessions: Session[] = [
  {
    id: "alpha-waves",
    title: "Calm & Centered",
    description: "Find your inner peace and release anxiety with soothing frequencies",
    duration: 15,
    frequency: "10",
    gradient: ["#667eea", "#764ba2"],
    targetEmotions: ["depressed", "anxious", "stressed", "calm"],
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Kangaroo_MusiQue_-_The_Neverwritten_Role_Playing_Game.mp3",
  },
  {
    id: "theta-healing",
    title: "Deep Emotional Healing",
    description: "Transform sadness into serenity with profound healing vibrations",
    duration: 20,
    frequency: "6",
    gradient: ["#f093fb", "#f5576c"],
    targetEmotions: ["sad", "anxious", "calm"],
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-assets/Epoq-Lepidoptera.ogg",
  },
  {
    id: "beta-focus",
    title: "Mental Clarity & Focus",
    description: "Sharpen your mind and boost concentration with energizing frequencies",
    duration: 10,
    frequency: "20",
    gradient: ["#4facfe", "#00f2fe"],
    targetEmotions: ["focused", "energized"],
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-demos/GalaxyInvaders/theme_01.mp3",
  },
  {
    id: "delta-sleep",
    title: "Peaceful Rest & Recovery",
    description: "Release stress and prepare for deep, restorative sleep",
    duration: 30,
    frequency: "2",
    gradient: ["#a8edea", "#fed6e3"],
    targetEmotions: ["depressed", "anxious", "stressed", "calm"],
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-assets/Erase_this_please_001.ogg",
  },
  {
    id: "gamma-insight",
    title: "Elevated Awareness",
    description: "Expand consciousness and unlock your highest potential",
    duration: 12,
    frequency: "40",
    gradient: ["#ffecd2", "#fcb69f"],
    targetEmotions: ["focused", "energized", "happy"],
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-demos/riceracer_assets/music/race2.ogg",
  },
  {
    id: "528hz-love",
    title: "Heart Opening & Love",
    description: "Open your heart to love and transform negative emotions",
    duration: 18,
    frequency: "528",
    gradient: ["#ff9a9e", "#fecfef"],
    targetEmotions: ["sad", "angry", "happy", "calm"],
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-assets/week7-brrring.m4a",
  },
  {
    id: "396hz-release",
    title: "Freedom from Fear",
    description: "Release limiting beliefs and embrace your authentic self",
    duration: 15,
    frequency: "396",
    gradient: ["#a1c4fd", "#c2e9fb"],
    targetEmotions: ["anxious", "stressed", "angry"],
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-demos/riceracer_assets/music/menu.ogg",
  },
  {
    id: "741hz-detox",
    title: "Emotional Cleansing",
    description: "Purify your emotional body and release toxic feelings",
    duration: 22,
    frequency: "741",
    gradient: ["#d299c2", "#fef9d7"],
    targetEmotions: ["angry", "sad", "stressed"],
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-assets/sounddogs/soundtrack.mp3",
  },
];