import { EmotionalState, Session } from "@/types/session";

export const emotionalStates: EmotionalState[] = [
  {
    id: "anxious",
    label: "Anxious",
    gradient: ["#FF6B6B", "#C44569"],
  },
  {
    id: "stressed",
    label: "Stressed",
    gradient: ["#F7971E", "#FFD200"],
  },
  {
    id: "sad",
    label: "Sad",
    gradient: ["#667eea", "#764ba2"],
  },
  {
    id: "angry",
    label: "Angry",
    gradient: ["#f093fb", "#f5576c"],
  },
  {
    id: "calm",
    label: "Calm",
    gradient: ["#4facfe", "#00f2fe"],
  },
  {
    id: "focused",
    label: "Focused",
    gradient: ["#43e97b", "#38f9d7"],
  },
  {
    id: "happy",
    label: "Happy",
    gradient: ["#fa709a", "#fee140"],
  },
  {
    id: "energized",
    label: "Energized",
    gradient: ["#30cfd0", "#330867"],
  },
];

export const sessions: Session[] = [
  {
    id: "alpha-waves",
    title: "Anxiousness to Peace",
    description: "Transform anxiety into deep peace with 10Hz alpha waves",
    duration: 15,
    frequency: "10",
    gradient: ["#667eea", "#764ba2"],
    targetEmotions: ["anxious", "stressed", "calm"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
  {
    id: "theta-healing",
    title: "Anxiousness to Calm",
    description: "Journey from anxiety to deep calm with 6Hz theta waves",
    duration: 20,
    frequency: "6",
    gradient: ["#f093fb", "#f5576c"],
    targetEmotions: ["sad", "anxious", "calm"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },
  {
    id: "beta-focus",
    title: "Beta Focus Booster",
    description: "Enhance concentration and mental clarity with 20Hz beta waves",
    duration: 10,
    frequency: "20",
    gradient: ["#4facfe", "#00f2fe"],
    targetEmotions: ["focused", "energized"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: "delta-sleep",
    title: "Anxiousness to Joy",
    description: "Transform anxiety into joyful tranquility with 2Hz delta waves",
    duration: 30,
    frequency: "2",
    gradient: ["#a8edea", "#fed6e3"],
    targetEmotions: ["anxious", "stressed", "calm"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: "gamma-insight",
    title: "Gamma Insight",
    description: "Heighten awareness and cognitive function with 40Hz gamma waves",
    duration: 12,
    frequency: "40",
    gradient: ["#ffecd2", "#fcb69f"],
    targetEmotions: ["focused", "energized", "happy"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
  {
    id: "528hz-love",
    title: "528Hz Love Frequency",
    description: "The miracle tone for transformation and DNA repair",
    duration: 18,
    frequency: "528",
    gradient: ["#ff9a9e", "#fecfef"],
    targetEmotions: ["sad", "angry", "happy", "calm"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },
  {
    id: "396hz-release",
    title: "Anxiousness to Happy",
    description: "Release anxiety and embrace happiness with this powerful solfeggio frequency",
    duration: 15,
    frequency: "396",
    gradient: ["#a1c4fd", "#c2e9fb"],
    targetEmotions: ["anxious", "stressed", "angry"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  },
  {
    id: "741hz-detox",
    title: "741Hz Emotional Detox",
    description: "Cleanse negative emotions and toxins from your energy field",
    duration: 22,
    frequency: "741",
    gradient: ["#d299c2", "#fef9d7"],
    targetEmotions: ["angry", "sad", "stressed"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  },
];